environment:
  matrix:
  - julia_version: 1.1
  - julia_version: 1.2
  - julia_version: 1.3
  - julia_version: latest
  - PYTHON: "C:\\Python36-x64"
    PYTHON_VERSION: "3.6.x" # currently 3.6.5
    PYTHON_ARCH: "64"

platform:

  - x64 # 64-bit

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia_version: latest
  - julia_version: 1.3

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - C:\julia\bin\julia --project --color=yes -e " using InteractiveUtils; versioninfo();
        import Pkg; Pkg.instantiate(); Pkg.build();"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia --check-bounds=yes --color=yes --project -e "%JL_TEST_SCRIPT%"